-- Catalog test data: synthetic edge cases + rows inserted by the ORIGINAL Next.js getModels() background seeding.
-- Captured from the scratch database the original TypeScript ran against (see golden/catalog-api-expected.json).
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('apple', 'Apple', 'https://upload.wikimedia.org/apple.svg', '{smartphone,tablet,watch}', 1);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('samsung', 'Samsung', 'https://upload.wikimedia.org/samsung.svg', '{smartphone,tv,watch}', 2);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('Xiaomi', 'Xiaomi DB', '/brands/xiaomi.svg', '{mobile}', 3);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('nokia', 'Nokia', '/brands/nokia.svg', '{}', 50);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('lg', 'LG', '/brands/lg.svg', NULL, 60);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('sony', 'Sony', '/brands/sony.svg', '{tv,console}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('boat', 'boAt', '/brands/boat.png', '{earbuds}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('acer', 'Acer', '/brands/acer.png', '{laptop}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('dell', 'dell', '/brands/dell.png', '{laptop}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('Dell2', 'Dell', '/brands/dell2.png', '{laptop}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('zeta', 'Zeta', '/brands/zeta.png', '{ipad}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('amazfit', 'Amazfit', '/brands/amazfit.png', '{smartwatch}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('tcl', 'TCL', '/brands/tcl.png', '{smarttv}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('xiaomi', 'Xiaomi', '/brands/xiaomi2.svg', '{smartphone,tv}', 3);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('realme', 'Realme', '/models/realme/Realme_GT_7_Pro_5G.png', '{smartphone}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('poco', 'Poco', '/models/poco/Poco_F7.png', '{smartphone}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('vivo', 'Vivo', '/models/vivo/Vivo_X300_Pro.png', '{smartphone}', 100);
INSERT INTO public."Brand" (id, name, logo, categories, priority) VALUES ('oneplus', 'Oneplus', '/models/oneplus/OnePlus_Nord_N20_SE.png', '{smartphone}', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-s26u', 'samsung', 'Galaxy S26 Ultra', 'https://upload.wikimedia.org/x.svg', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-s21', 'samsung', 'Galaxy S21', 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-5g-r.jpg', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-tab', 'samsung', 'Galaxy Tab S8', 'https://fdn2.gsmarena.com/tab.jpg', 'tablet', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-gw5', 'samsung', 'Galaxy Watch 5', 'https://fdn2.gsmarena.com/w5.jpg', 'watch', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-qled', 'samsung', 'QLED 4K Smart TV', 'https://images.samsung.com/qled.png', 'tv', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-neo', 'samsung', 'Neo QLED', '/models/samsung/neo.png', 'smarttv', 90);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ip13', 'apple', 'iPhone 13', '', 'mobile', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ip14', 'apple', 'iPhone 14', 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg', '', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ipad', 'apple', 'iPad Pro 11"', 'https://fdn2.gsmarena.com/ipad.jpg', 'ipad', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-aw8', 'apple', 'Watch Series 8', 'https://fdn2.gsmarena.com/aw8.jpg', 'smartwatch', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-mba', 'apple', 'MacBook Air', '/models/apple/mba.png', 'laptop', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ip15a', 'apple', 'iphone 15', '/models/apple/ip15a.png', 'smartphone', 5);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ip15b', 'apple', 'iPhone 15', '/models/apple/ip15b.png', 'smartphone', 5);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ip15p', 'apple', 'iPhone 15 Pro', 'Logo.png', 'Smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-rn15', 'xiaomi', 'Redmi Note 15 Pro+ 5G', '/models/xiaomi/db.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-mi11x', 'xiaomi', 'Mi 11X', 'https://fdn2.gsmarena.com/mi11x.jpg', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-t1', 'boat', 'Test_Model', '/x/t1.png', 'earbuds', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-t2', 'boat', 'TestaModel', '/x/t2.png', 'earbuds', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-t3', 'boat', 'Promo 50% Bundle', '/x/t3.png', 'earbuds', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-t4', 'boat', 'Promo 50 Bundle', '/x/t4.png', 'earbuds', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga01', 'samsung', 'Galaxy A01', '/g/1.png', 'smartphone', 30);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga02', 'samsung', 'Galaxy A02', '/g/2.png', 'smartphone', 20);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga03', 'samsung', 'Galaxy A03', '/g/3.png', 'smartphone', 40);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga04', 'samsung', 'Galaxy A04', '/g/4.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga05', 'samsung', 'Galaxy A05', '/g/5.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga06', 'samsung', 'galaxy a06', '/g/6.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga07', 'samsung', 'Galaxy A07', '/g/7.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga08', 'samsung', 'Galaxy A08', '/g/8.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga09', 'samsung', 'Galaxy A09', '/g/9.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga10', 'samsung', 'Galaxy A10', '/g/10.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga11', 'samsung', 'Galaxy A11', '/g/11.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-ga12', 'samsung', 'Galaxy A12', '/g/12.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-lg', 'lg', 'LG Wing', '/lg.png', 'smartphone', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-nk', 'nokia', 'Nokia G42', '/nk.png', 'mobile', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('m-sony', 'sony', 'PlayStation 5', 'https://gmedia.playstation.com/ps5.png', 'console', 100);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('galaxy-s26-plus-5g', 'samsung', 'Galaxy S26+ 5G', '/models/samsung/Samsung_Galaxy_S25_Plus.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('galaxy-s26-5g', 'samsung', 'Galaxy S26 5G', '/models/samsung/Samsung_Galaxy_S25.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('galaxy-z-fold-8-ultra', 'samsung', 'Galaxy Z Fold 8 Ultra', '/models/samsung/Samsung_Galaxy_Z_Fold_7.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('galaxy-z-fold-8', 'samsung', 'Galaxy Z Fold 8', '/models/samsung/Samsung_Galaxy_Z_Fold_6.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('galaxy-z-flip-8', 'samsung', 'Galaxy Z Flip 8', '/models/samsung/Samsung_Galaxy_Z_Flip_7.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('galaxy-f70-pro-5g', 'samsung', 'Galaxy F70 Pro 5G', '/models/samsung/Samsung_Galaxy_F56_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('galaxy-m47-5g', 'samsung', 'Galaxy M47 5G', '/models/samsung/Samsung_Galaxy_M56_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('galaxy-a86-5g', 'samsung', 'Galaxy A86 5G', '/models/samsung/Samsung_Galaxy_A56_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('redmi-turbo-5', 'xiaomi', 'Redmi Turbo 5', '/models/xiaomi/Xiaomi_15.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('redmi-note-15-pro-5g', 'xiaomi', 'Redmi Note 15 Pro 5G', '/models/xiaomi/Redmi_Note_15_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('redmi-note-17-5g', 'xiaomi', 'Redmi Note 17 5G', '/models/xiaomi/Redmi_Note_14_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-gt6-5g', 'realme', 'Realme GT6 5G', '/models/realme/Realme_GT_6.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-narzo-80-pro', 'realme', 'Realme Narzo 80 Pro', '/models/realme/Realme_Narzo_80_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-x300-ultra', 'vivo', 'Vivo X300 Ultra', '/models/vivo/Vivo_X300_Pro.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-m8-5g', 'poco', 'POCO M8 5G', '/models/poco/Poco_M8_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-x300-fe-5g', 'vivo', 'Vivo X300 FE 5G', '/models/vivo/Vivo_X200_FE.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('redmi-note-15-5g', 'xiaomi', 'Redmi Note 15 5G', '/models/xiaomi/Redmi_Note_15_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('redmi-15c-5g', 'xiaomi', 'Redmi 15C 5G', '/models/xiaomi/Redmi_15C_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-gt6-pro-5g', 'realme', 'Realme GT6 Pro 5G', '/models/realme/Realme_GT_7_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-14-pro-plus-5g', 'realme', 'Realme 14 Pro+ 5G', '/models/realme/Realme_14_Pro_Plus_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-c75-5g', 'realme', 'Realme C75 5G', '/models/realme/Realme_C75_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-c8-5g', 'poco', 'POCO C8 5G', '/models/poco/Poco_C75_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-narzo-80x-5g', 'realme', 'Realme Narzo 80x 5G', '/models/realme/Realme_Narzo_80X_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-f8-pro-5g', 'poco', 'POCO F8 Pro 5G', '/models/poco/Poco_F7.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-f8-5g', 'poco', 'POCO F8 5G', '/models/poco/Poco_F6_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-f8-gt-5g', 'poco', 'POCO F8 GT 5G', '/models/poco/POCO_F3_GT.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-x8-pro-5g', 'poco', 'POCO X8 Pro 5G', '/models/poco/Poco_X7_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-x800', 'vivo', 'Vivo X800', '/models/vivo/Vivo_X300_Pro.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-x200-pro', 'vivo', 'Vivo X200 Pro', '/models/vivo/Vivo_X200_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('oneplus-nord-ce-6-lite', 'oneplus', 'OnePlus Nord CE 6 Lite', '/models/oneplus/OnePlus_Nord_CE4_Lite_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-v60e-5g', 'vivo', 'Vivo V60e 5G', '/models/vivo/Vivo_V60e.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-t50-pro-5g', 'vivo', 'Vivo T50 Pro 5G', '/models/vivo/Vivo_T4_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-y11-5g', 'vivo', 'Vivo Y11 5G', '/models/vivo/Vivo_Y11_2019.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('redmi-note-15-se-5g', 'xiaomi', 'Redmi Note 15 SE 5G', '/models/xiaomi/Redmi_Note_14_SE_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('redmi-15a-5g', 'xiaomi', 'Redmi 15A 5G', '/models/xiaomi/Redmi_15_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-gt-neo-8-5g', 'realme', 'Realme GT Neo 8 5G', '/models/realme/REALME_GT_NEO_3_150W.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-x300-pro-5g', 'vivo', 'Vivo X300 Pro 5G', '/models/vivo/Vivo_X300_Pro.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('oneplus-n6', 'oneplus', 'OnePlus N6', '/models/oneplus/OnePlus_Nord_N20_SE.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-x200t', 'vivo', 'Vivo X200T', '/models/vivo/Vivo_X200T.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-v70-5g', 'vivo', 'Vivo V70 5G', '/models/vivo/Vivo_V60_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('oneplus-15r', 'oneplus', 'OnePlus 15R', '/models/oneplus/Oneplus_15R.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-v60-5g', 'vivo', 'Vivo V60 5G', '/models/vivo/Vivo_V60_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-y81-5g', 'vivo', 'Vivo Y81 5G', '/models/vivo/Vivo_Y81.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-y500-pro', 'vivo', 'Vivo Y500 Pro', '/models/vivo/Vivo_Y400_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-14-pro-5g', 'realme', 'Realme 14 Pro 5G', '/models/realme/Realme_14_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-x8-5g', 'poco', 'POCO X8 5G', '/models/poco/Poco_X7_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-x8-neo-5g', 'poco', 'POCO X8 Neo 5G', '/models/poco/Poco_X6_Neo.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-x300-fe-ultra', 'vivo', 'Vivo X300 FE Ultra', '/models/vivo/Vivo_X300_Pro.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-m8-pro-5g', 'poco', 'POCO M8 Pro 5G', '/models/poco/Poco_M7_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-x300-5g', 'vivo', 'Vivo X300 5G', '/models/vivo/Vivo_X300.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-t5-lite-5g', 'vivo', 'Vivo T5 Lite 5G', '/models/vivo/Vivo_T4_Lite_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-y500-5g', 'vivo', 'Vivo Y500 5G', '/models/vivo/Vivo_Y300_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('poco-c8-plus', 'poco', 'POCO C8 Plus', '/models/poco/POCO_C85.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('oneplus-nord-ce-6-5g', 'oneplus', 'OnePlus Nord CE 6 5G', '/models/oneplus/OnePlus_Nord_CE_5_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-v70-fe', 'vivo', 'Vivo V70 FE', '/models/vivo/Vivo_V50_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-t5e', 'vivo', 'Vivo T5e', '/models/vivo/Vivo_T4_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-s2-5g', 'vivo', 'Vivo S2 5G', '/models/vivo/Vivo_S1_Pro.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-y51-pro-5g', 'vivo', 'Vivo Y51 Pro 5G', '/models/vivo/Vivo_Y51A.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-v70-elite', 'vivo', 'Vivo V70 Elite', '/models/vivo/Vivo_V60_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-t5x-5g', 'vivo', 'Vivo T5x 5G', '/models/vivo/Vivo_T4x_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-y05', 'vivo', 'Vivo Y05', '/models/vivo/Vivo_Y01.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-y600-pro', 'vivo', 'Vivo Y600 Pro', '/models/vivo/Vivo_Y400_Pro_5G.png', 'smartphone', 10);
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('vivo-s50-mini', 'vivo', 'Vivo S50 / Mini', '/models/vivo/Vivo_S1.png', 'smartphone', 10);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('v-s21-256', 'm-s21', '8GB + 256GB', 32000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('v-s21-128', 'm-s21', '8GB + 128GB', 30000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('v-ip13-128', 'm-ip13', '128GB', 29960);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('v-ip13-256', 'm-ip13', '256GB', 30860);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('v-t1', 'm-t1', '50%_off', 100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('v-t2', 'm-t2', '50x off', 200);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('v-mba', 'm-mba', '8GB/256GB', 45000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('v-ip15a', 'm-ip15a', '128GB', 40000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-s26-plus-5g-12-256', 'galaxy-s26-plus-5g', '12GB + 256GB', 56100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-s26-plus-5g-12-512', 'galaxy-s26-plus-5g', '12GB + 512GB', 59000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-s26-5g-12-128', 'galaxy-s26-5g', '12GB + 128GB', 44880);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-s26-5g-12-256', 'galaxy-s26-5g', '12GB + 256GB', 47000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-z-fold-8-12-256', 'galaxy-z-fold-8', '12GB + 256GB', 89760);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-z-fold-8-ultra-16-512', 'galaxy-z-fold-8-ultra', '16GB + 512GB', 100980);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-z-fold-8-ultra-16-1tb', 'galaxy-z-fold-8-ultra', '16GB + 1TB', 108000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-z-fold-8-12-512', 'galaxy-z-fold-8', '12GB + 512GB', 94000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-z-flip-8-12-256', 'galaxy-z-flip-8', '12GB + 256GB', 56100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-z-flip-8-12-512', 'galaxy-z-flip-8', '12GB + 512GB', 59000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-f70-pro-5g-8-128', 'galaxy-f70-pro-5g', '8GB + 128GB', 14025);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-f70-pro-5g-8-256', 'galaxy-f70-pro-5g', '8GB + 256GB', 15500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-m47-5g-6-128', 'galaxy-m47-5g', '6GB + 128GB', 11220);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-m47-5g-8-128', 'galaxy-m47-5g', '8GB + 128GB', 12000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-a86-5g-8-128', 'galaxy-a86-5g', '8GB + 128GB', 22440);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('galaxy-a86-5g-8-256', 'galaxy-a86-5g', '8GB + 256GB', 24000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-turbo-5-8-256', 'redmi-turbo-5', '8GB + 256GB', 23562);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-turbo-5-12-256', 'redmi-turbo-5', '12GB + 256GB', 25000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-note-15-pro-5g-8-128', 'redmi-note-15-pro-5g', '8GB + 128GB', 19635);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-note-15-pro-5g-8-256', 'redmi-note-15-pro-5g', '8GB + 256GB', 21000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-note-15-5g-6-128', 'redmi-note-15-5g', '6GB + 128GB', 15147);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-note-15-5g-8-256', 'redmi-note-15-5g', '8GB + 256GB', 16500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-note-15-se-5g-6-128', 'redmi-note-15-se-5g', '6GB + 128GB', 14586);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-note-15-se-5g-8-128', 'redmi-note-15-se-5g', '8GB + 128GB', 15500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-note-17-5g-8-128', 'redmi-note-17-5g', '8GB + 128GB', 17391);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-note-17-5g-8-256', 'redmi-note-17-5g', '8GB + 256GB', 18500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-15c-5g-6-128', 'redmi-15c-5g', '6GB + 128GB', 10378);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-15c-5g-8-128', 'redmi-15c-5g', '8GB + 128GB', 11000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-15a-5g-4-128', 'redmi-15a-5g', '4GB + 128GB', 8592);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('redmi-15a-5g-6-128', 'redmi-15a-5g', '6GB + 128GB', 9200);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-gt6-pro-5g-12-256', 'realme-gt6-pro-5g', '12GB + 256GB', 33660);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-gt6-pro-5g-16-512', 'realme-gt6-pro-5g', '16GB + 512GB', 36000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-gt6-5g-8-256', 'realme-gt6-5g', '8GB + 256GB', 23001);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-gt6-5g-12-256', 'realme-gt6-5g', '12GB + 256GB', 25000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-gt-neo-8-5g-8-256', 'realme-gt-neo-8-5g', '8GB + 256GB', 20196);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-gt-neo-8-5g-12-256', 'realme-gt-neo-8-5g', '12GB + 256GB', 21500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-14-pro-plus-5g-8-256', 'realme-14-pro-plus-5g', '8GB + 256GB', 18513);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-14-pro-plus-5g-12-256', 'realme-14-pro-plus-5g', '12GB + 256GB', 19500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-14-pro-5g-8-128', 'realme-14-pro-5g', '8GB + 128GB', 15708);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-14-pro-5g-8-256', 'realme-14-pro-5g', '8GB + 256GB', 16800);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-narzo-80-pro-8-128', 'realme-narzo-80-pro', '8GB + 128GB', 12903);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-narzo-80-pro-8-256', 'realme-narzo-80-pro', '8GB + 256GB', 14000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-narzo-80x-5g-6-128', 'realme-narzo-80x-5g', '6GB + 128GB', 8976);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-narzo-80x-5g-8-128', 'realme-narzo-80x-5g', '8GB + 128GB', 9500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-c75-5g-4-128', 'realme-c75-5g', '4GB + 128GB', 7293);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-c75-5g-6-128', 'realme-c75-5g', '6GB + 128GB', 7900);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-f8-pro-5g-12-256', 'poco-f8-pro-5g', '12GB + 256GB', 25245);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-f8-pro-5g-16-512', 'poco-f8-pro-5g', '16GB + 512GB', 27500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-f8-5g-8-256', 'poco-f8-5g', '8GB + 256GB', 19635);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-f8-5g-12-256', 'poco-f8-5g', '12GB + 256GB', 21000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-f8-gt-5g-8-256', 'poco-f8-gt-5g', '8GB + 256GB', 22440);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-f8-gt-5g-12-256', 'poco-f8-gt-5g', '12GB + 256GB', 24000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-x8-pro-5g-8-256', 'poco-x8-pro-5g', '8GB + 256GB', 16269);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-x8-pro-5g-12-256', 'poco-x8-pro-5g', '12GB + 256GB', 17500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-x8-5g-8-128', 'poco-x8-5g', '8GB + 128GB', 12342);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-x8-5g-8-256', 'poco-x8-5g', '8GB + 256GB', 13500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-ultra-12-256', 'vivo-x300-ultra', '12GB + 256GB', 56100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-x8-neo-5g-6-128', 'poco-x8-neo-5g', '6GB + 128GB', 10098);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-ultra-16-512', 'vivo-x300-ultra', '16GB + 512GB', 60000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-x8-neo-5g-8-256', 'poco-x8-neo-5g', '8GB + 256GB', 11000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-m8-pro-5g-6-128', 'poco-m8-pro-5g', '6GB + 128GB', 8415);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-pro-5g-12-256', 'vivo-x300-pro-5g', '12GB + 256GB', 48000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-m8-pro-5g-8-128', 'poco-m8-pro-5g', '8GB + 128GB', 9000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-pro-5g-16-512', 'vivo-x300-pro-5g', '16GB + 512GB', 63600);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-5g-8-256', 'vivo-x300-5g', '8GB + 256GB', 36465);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-m8-5g-4-128', 'poco-m8-5g', '4GB + 128GB', 6732);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-5g-12-256', 'vivo-x300-5g', '12GB + 256GB', 39000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-m8-5g-6-128', 'poco-m8-5g', '6GB + 128GB', 7200);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-fe-5g-12-256', 'vivo-x300-fe-5g', '12GB + 256GB', 49800);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-c8-5g-4-128', 'poco-c8-5g', '4GB + 128GB', 5610);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-fe-5g-12-512', 'vivo-x300-fe-5g', '12GB + 512GB', 54800);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-c8-5g-6-128', 'poco-c8-5g', '6GB + 128GB', 6000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x300-fe-ultra-16-512', 'vivo-x300-fe-ultra', '16GB + 512GB', 80000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-c8-plus-4-64', 'poco-c8-plus', '4GB + 64GB', 5049);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('poco-c8-plus-4-128', 'poco-c8-plus', '4GB + 128GB', 5500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x800-12-256', 'vivo-x800', '12GB + 256GB', 46800);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x800-12-512', 'vivo-x800', '12GB + 512GB', 47400);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-n6-4-128', 'oneplus-n6', '4GB + 128GB', 16000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x800-16-512', 'vivo-x800', '16GB + 512GB', 50000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x200t-12-256', 'vivo-x200t', '12GB + 256GB', 38100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-n6-6-256', 'oneplus-n6', '6GB + 256GB', 17300);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-nord-ce-6-5g-6-128', 'oneplus-nord-ce-6-5g', '6GB + 128GB', 18400);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x200t-12-512', 'vivo-x200t', '12GB + 512GB', 42200);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-nord-ce-6-5g-8-128', 'oneplus-nord-ce-6-5g', '8GB + 128GB', 19000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x200-pro-12-256', 'vivo-x200-pro', '12GB + 256GB', 39270);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-nord-ce-6-5g-12-256', 'oneplus-nord-ce-6-5g', '12GB + 256GB', 19500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-x200-pro-12-512', 'vivo-x200-pro', '12GB + 512GB', 42000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-nord-ce-6-lite-6-128', 'oneplus-nord-ce-6-lite', '6GB + 128GB', 16700);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v70-5g-8-256', 'vivo-v70-5g', '8GB + 256GB', 33200);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-nord-ce-6-lite-8-128', 'oneplus-nord-ce-6-lite', '8GB + 128GB', 18600);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v70-5g-12-256', 'vivo-v70-5g', '12GB + 256GB', 36000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-15r-16-512', 'oneplus-15r', '16GB + 512GB', 37500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v70-elite-8-256', 'vivo-v70-elite', '8GB + 256GB', 36000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y500-pro-6-128', 'vivo-y500-pro', '6GB + 128GB', 10098);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y500-pro-8-128', 'vivo-y500-pro', '8GB + 128GB', 11000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-nord-ce-6-lite-8-256', 'oneplus-nord-ce-6-lite', '8GB + 256GB', 20100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t5x-5g-8-128', 'vivo-t5x-5g', '8GB + 128GB', 18200);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t5-lite-5g-4-128', 'vivo-t5-lite-5g', '4GB + 128GB', 7854);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t5-lite-5g-6-128', 'vivo-t5-lite-5g', '6GB + 128GB', 8500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-s2-5g-8-256', 'vivo-s2-5g', '8GB + 256GB', 18513);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y81-5g-6-128', 'vivo-y81-5g', '6GB + 128GB', 14400);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y05-4-64', 'vivo-y05', '4GB + 64GB', 10000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('oneplus-15r-12-256', 'oneplus-15r', '12GB + 256GB', 35600);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v70-elite-12-256', 'vivo-v70-elite', '12GB + 256GB', 39100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t50-pro-5g-8-128', 'vivo-t50-pro-5g', '8GB + 128GB', 14025);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v70-elite-12-512', 'vivo-v70-elite', '12GB + 512GB', 41700);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v70-fe-8-256', 'vivo-v70-fe', '8GB + 256GB', 26800);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v70-fe-12-256', 'vivo-v70-fe', '12GB + 256GB', 30100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y51-pro-5g-8-256', 'vivo-y51-pro-5g', '8GB + 256GB', 20100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y11-5g-4-64', 'vivo-y11-5g', '4GB + 64GB', 10100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y11-5g-4-128', 'vivo-y11-5g', '4GB + 128GB', 11600);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y600-pro-8-128', 'vivo-y600-pro', '8GB + 128GB', 12342);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v70-fe-8-128', 'vivo-v70-fe', '8GB + 128GB', 24500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v60-5g-8-256', 'vivo-v60-5g', '8GB + 256GB', 19000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v60e-5g-8-256', 'vivo-v60e-5g', '8GB + 256GB', 15500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t50-pro-5g-8-256', 'vivo-t50-pro-5g', '8GB + 256GB', 15000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t5e-6-128', 'vivo-t5e', '6GB + 128GB', 11220);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y51-pro-5g-8-128', 'vivo-y51-pro-5g', '8GB + 128GB', 17700);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y81-5g-4-128', 'vivo-y81-5g', '4GB + 128GB', 13500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y81-5g-8-128', 'vivo-y81-5g', '8GB + 128GB', 16100);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y500-5g-6-128', 'vivo-y500-5g', '6GB + 128GB', 8415);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v60-5g-8-128', 'vivo-v60-5g', '8GB + 128GB', 17952);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-v60e-5g-8-128', 'vivo-v60e-5g', '8GB + 128GB', 14586);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-s2-5g-12-256', 'vivo-s2-5g', '12GB + 256GB', 19800);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-s50-mini-8-256', 'vivo-s50-mini', '8GB + 256GB', 16800);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t5x-5g-6-128', 'vivo-t5x-5g', '6GB + 128GB', 15300);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t5x-5g-8-256', 'vivo-t5x-5g', '8GB + 256GB', 19000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-t5e-8-128', 'vivo-t5e', '8GB + 128GB', 12000);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-s50-mini-8-128', 'vivo-s50-mini', '8GB + 128GB', 15708);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y600-pro-8-256', 'vivo-y600-pro', '8GB + 256GB', 13500);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('vivo-y500-5g-8-128', 'vivo-y500-5g', '8GB + 128GB', 9000);
-- Saved by getModels() background seeding once matching became brand-aware (2026-10-06): before, the Apple
-- "iPhone 14" row above made the catalog's "Realme 14 5G" look already present (both reduce to the name key "14").
INSERT INTO public."Model" (id, "brandId", name, img, category, priority) VALUES ('realme-14-5g', 'realme', 'Realme 14 5G', '/models/realme/Realme_14X_5G.png', 'smartphone', 10);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-14-5g-6-128', 'realme-14-5g', '6GB + 128GB', 11220);
INSERT INTO public."Variant" (id, "modelId", name, "basePrice") VALUES ('realme-14-5g-8-128', 'realme-14-5g', '8GB + 128GB', 12000);
