// Builds the private copy of the website code that the security tests run against (inside the container only).
//   node prepare.mjs <project root> <destination> [--originals]
// UI components are replaced by placeholders that keep their export names: pages are run as plain functions and
// the tests only read the props they pass to each component, so no browser libraries are needed.
// --originals overlays security-hardening/originals/*.orig, i.e. the code from before this hardening, to show that
// the tests detect the vulnerabilities.
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

const [src, dest, flag] = process.argv.slice(2);
mkdirSync(dest, { recursive: true });

for (const entry of ['actions', 'app', 'components', 'lib', 'prisma', 'scripts', 'tsconfig.json']) {
    cpSync(join(src, entry), join(dest, entry), {
        recursive: true,
        filter: p => !/[\\/](node_modules|\.next)([\\/]|$)/.test(p),
    });
}
writeFileSync(join(dest, 'package.json'), JSON.stringify({ name: 'fonzkart-under-test', private: true }));

function* files(dir) {
    for (const name of readdirSync(dir)) {
        const p = join(dir, name);
        if (statSync(p).isDirectory()) yield* files(p);
        else yield p;
    }
}

let placeholders = 0;
for (const file of files(join(dest, 'components'))) {
    if (!file.endsWith('.tsx')) continue;
    const code = readFileSync(file, 'utf8');
    let hasDefault = /export\s+default\b/.test(code);
    const names = new Set();
    for (const m of code.matchAll(/export\s+(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z_$][\w$]*)/g)) names.add(m[1]);
    for (const m of code.matchAll(/export\s*\{([^}]*)\}/g)) {
        for (const part of m[1].split(',')) {
            const name = part.trim().split(/\s+as\s+/).pop();
            if (name === 'default') hasDefault = true;
            else if (name) names.add(name);
        }
    }
    let out = '// Placeholder generated by scripts/security-tests/prepare.mjs\n';
    if (hasDefault) out += 'export default function Placeholder(_props: any) { return null; }\n';
    for (const name of names) out += `export function ${name}(_props: any) { return null; }\n`;
    writeFileSync(file, out);
    placeholders++;
}

let overlaid = 0;
if (flag === '--originals') {
    const originals = join(src, 'security-hardening', 'originals');
    for (const file of files(originals)) {
        if (!file.endsWith('.orig')) continue;
        const target = join(dest, relative(originals, file).replace(/\.orig$/, ''));
        mkdirSync(dirname(target), { recursive: true });
        writeFileSync(target, readFileSync(file));
        overlaid++;
    }
}

console.log(`prepared ${dest}: ${placeholders} UI components replaced by placeholders`
    + (flag === '--originals' ? `, ${overlaid} files restored to their pre-hardening version` : ''));
if (!existsSync(join(dest, 'tsconfig.json'))) throw new Error('tsconfig.json missing');
