// Writes executive tokens produced by the website (lib/executive-session.ts, jose) for fixed inputs, so the Spring
// Boot backend can prove it signs byte-for-byte identical tokens and accepts the website's.
//   tsx scripts/security-tests/token-fixture.ts <out.json>
import { writeFileSync } from 'node:fs';
import { EXECUTIVE_TOKEN_LIFETIME_SECONDS, signExecutiveToken } from '@/lib/executive-session';

async function main() {
    const cases = [
        { riderId: 'r1', iat: 1767225600 },
        { riderId: 'cm4x9k2p00001abcd5678efgh', iat: 1790000000 },
        { riderId: 'rider-ü-✓', iat: 1800000000 },
    ];
    const tokens = [];
    for (const c of cases) tokens.push({ ...c, exp: c.iat + EXECUTIVE_TOKEN_LIFETIME_SECONDS, token: await signExecutiveToken(c.riderId, c.iat) });
    writeFileSync(process.argv[2], JSON.stringify({
        description: 'Executive tokens signed by lib/executive-session.ts with AUTH_SECRET below; generated by scripts/security-tests/run.sh golden.',
        secret: process.env.AUTH_SECRET,
        tokens,
    }, null, 1));
    console.log('tokens:', tokens.length);
}
main().catch(e => { console.error(e); process.exit(1); });
